stages:
  - test
unit-test:
  script:
    "/home/unity_8R_11_82EIPokw/Unity/Hub/Editor/2022.3.26f1/Unity \
    -batchmode \
    -projectPath . \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml"
  stage: test
  tags:
    - unity